# Generated by Django 5.2.9 on 2026-01-28 07:33

import accounts.models
import django.contrib.gis.db.models.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('CITIZEN', 'Citizen'), ('COMMUNITY_LEADER', 'Community Leader'), ('LAW_ENFORCEMENT', 'Law Enforcement'), ('NGO_PARTNER', 'NGO Partner'), ('HQ_ADMIN', 'HQ Admin'), ('INVESTIGATOR', 'Investigator')], default='CITIZEN', max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('live_photo', models.ImageField(blank=True, null=True, upload_to='users/live_photos/')),
                ('preferred_language', models.CharField(default='en', max_length=20)),
                ('last_known_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Last known GPS/IP-based location', null=True, srid=4326)),
                ('location_source', models.CharField(choices=[('GPS', 'GPS'), ('IP', 'IP'), ('MANUAL', 'Manual'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('location_confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('imei', models.CharField(blank=True, max_length=50, null=True)),
                ('sim_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_model', models.CharField(blank=True, max_length=100)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('lock_until', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('NGO', 'NGO'), ('GOVERNMENT', 'Government'), ('NON_PROFIT', 'Non-profit'), ('COMMUNITY', 'Community'), ('OTHER', 'Other')], max_length=20)),
                ('org_type_other', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('RESET', 'Password Reset'), ('VERIFY', 'Account Verification')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.verification_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
