# Generated by Django 5.2.9 on 2026-02-01 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('community', '0008_emergencysharesession_privateconversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedUsername',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username_lower', models.CharField(db_index=True, max_length=32, unique=True)),
                ('reserved_type', models.CharField(choices=[('SYSTEM', 'System Only'), ('RESTRICTED', 'Restricted'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsernameRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('username_lower', models.CharField(db_index=True, max_length=32, unique=True)),
                ('entity_type', models.CharField(choices=[('USER', 'User'), ('HUB', 'Community Hub'), ('ORG', 'Organization'), ('RESPONDER', 'Responder'), ('SYSTEM', 'System')], max_length=20)),
                ('tier', models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted'), ('SYSTEM', 'System Reserved')], default='PUBLIC', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('LOCKED', 'Locked')], default='ACTIVE', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_changed_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usernames_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usernames_created', to=settings.AUTH_USER_MODEL)),
                ('hub', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_username', to='community.communityhub')),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_username', to='accounts.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_username', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['username_lower'], name='accounts_us_usernam_587349_idx'), models.Index(fields=['tier'], name='accounts_us_tier_a369e1_idx'), models.Index(fields=['entity_type'], name='accounts_us_entity__cc3307_idx'), models.Index(fields=['status'], name='accounts_us_status_db79ed_idx')],
            },
        ),
    ]
