# Generated by Django 5.2.9 on 2026-01-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_verificationdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='identifier',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
