# Generated by Django 5.2.9 on 2026-02-01 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_reservedusername_usernameregistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emergency_mode_enabled', models.BooleanField(default=False)),
                ('tracking_enabled', models.BooleanField(default=True)),
                ('location_enabled', models.BooleanField(default=True)),
                ('allow_location_sharing', models.BooleanField(default=True)),
                ('allow_anonymous_reports', models.BooleanField(default=True)),
                ('allow_push_notifications', models.BooleanField(default=True)),
                ('allow_messages_from', models.CharField(choices=[('EVERYONE', 'Everyone'), ('CONTACTS_ONLY', 'Contacts Only'), ('VERIFIED_ONLY', 'Verified Only')], default='EVERYONE', max_length=20)),
                ('allow_device_binding', models.BooleanField(default=True)),
                ('allow_media_upload', models.BooleanField(default=True)),
                ('searchable_by_username', models.BooleanField(default=True)),
                ('hide_last_seen', models.BooleanField(default=False)),
                ('sos_silent_mode', models.BooleanField(default=False)),
                ('sos_countdown_seconds', models.PositiveIntegerField(default=5)),
                ('sos_auto_call_enabled', models.BooleanField(default=False)),
                ('sos_auto_share_location', models.BooleanField(default=True)),
                ('sos_auto_record_audio', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.CharField(blank=True, max_length=10, null=True)),
                ('quiet_hours_end', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='accounts_ac_user_id_a60b12_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('relationship', models.CharField(blank=True, choices=[('FAMILY', 'Family'), ('FRIEND', 'Friend'), ('NEIGHBOR', 'Neighbor'), ('COLLEAGUE', 'Colleague'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='accounts_em_user_id_4e5240_idx'), models.Index(fields=['verified'], name='accounts_em_verifie_76ef3f_idx')],
            },
        ),
    ]
