# Generated by Django 5.2.9 on 2026-02-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profilesettings_accountdeletionrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='preferred_language',
            field=models.CharField(default='en', max_length=20),
        ),
    ]
