# Generated by Django 5.2.9 on 2026-01-28 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(choices=[('USER', 'User'), ('RESPONDER', 'Responder'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], default='USER', max_length=20)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTP_VERIFY', 'OTP Verify'), ('SUSPEND', 'Suspend'), ('EXPORT', 'Export'), ('ACCESS_DENIED', 'Access Denied'), ('STREAM_START', 'Stream Started'), ('STREAM_END', 'Stream Ended'), ('STREAM_VIEW', 'Stream Viewed'), ('STREAM_RECORDING_READY', 'Recording Ready'), ('RESPONDER_JOIN', 'Responder Joined'), ('RESPONDER_LEAVE', 'Responder Left'), ('RESPONDER_ACK', 'Responder Acknowledged'), ('SEVERITY_UPDATE', 'Severity Updated'), ('NETWORK_LOST', 'Network Lost'), ('OTHER', 'Other')], max_length=50)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('stream_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['stream_id'], name='audit_audit_stream__832f66_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx')],
            },
        ),
    ]
