# Generated by Django 5.2.9 on 2026-01-26 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_role',
            field=models.CharField(choices=[('USER', 'User'), ('RESPONDER', 'Responder'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], default='USER', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='stream_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTP_VERIFY', 'OTP Verify'), ('SUSPEND', 'Suspend'), ('EXPORT', 'Export'), ('ACCESS_DENIED', 'Access Denied'), ('STREAM_START', 'Stream Started'), ('STREAM_END', 'Stream Ended'), ('STREAM_VIEW', 'Stream Viewed'), ('STREAM_RECORDING_READY', 'Recording Ready'), ('RESPONDER_JOIN', 'Responder Joined'), ('RESPONDER_LEAVE', 'Responder Left'), ('RESPONDER_ACK', 'Responder Acknowledged'), ('SEVERITY_UPDATE', 'Severity Updated'), ('NETWORK_LOST', 'Network Lost'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_audit_action_86e815_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['stream_id'], name='audit_audit_stream__832f66_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'),
        ),
    ]
