# Generated by Django 5.2.9 on 2026-01-28 07:33

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(db_index=True, help_text='ISO-3166-1 alpha-2 country code (e.g. NG, US)', max_length=2)),
                ('admin_level', models.PositiveSmallIntegerField(db_index=True, help_text='Administrative level (0, 1, 2, ...)')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, help_text='Stable GADM identifier (GID)', max_length=64)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('eng_type', models.CharField(blank=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='community.adminunit')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityHub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hub_type', models.CharField(choices=[('SYSTEM', 'System (Geographic)'), ('LOCAL', 'Local / User Created')], default='LOCAL', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_unit', models.OneToOneField(blank=True, help_text='Linked geographic admin unit (for SYSTEM hubs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub', to='community.adminunit')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='community.communityhub')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('LEADER', 'Leader'), ('MODERATOR', 'Moderator')], default='MEMBER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.communityhub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='adminunit',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='adminunit_geom_gist'),
        ),
        migrations.AlterUniqueTogether(
            name='adminunit',
            unique_together={('country_code', 'admin_level', 'code')},
        ),
        migrations.AddConstraint(
            model_name='communityhub',
            constraint=models.UniqueConstraint(condition=models.Q(('hub_type', 'SYSTEM')), fields=('admin_unit',), name='unique_system_hub_per_admin_unit'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymembership',
            unique_together={('user', 'hub')},
        ),
    ]
