# Generated by Django 5.2.9 on 2026-01-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminunit',
            old_name='admin_level',
            new_name='level',
        ),
        migrations.AlterUniqueTogether(
            name='adminunit',
            unique_together={('country_code', 'level', 'code')},
        ),
    ]
