# Generated by Django 5.2.9 on 2026-01-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_admin_level_adminunit_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminunit',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
