# Generated by Django 5.2.9 on 2026-01-31 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_hubmessage_forwarded_from_hubmessage_is_forwarded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityhub',
            name='active_members_7d',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='ad_slots_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='alert_mode_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='alert_priority_default',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='allow_anonymous_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='allow_forwarding_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='allow_guest_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='allow_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='allow_location_sharing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='allow_media',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='allow_screenshots',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='allowed_lga_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='allowed_state_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='attachments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='audit_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='audit_retention_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='auto_moderation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='avatar_icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='banned_words',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=80),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='donation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='emergency_contacts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='engagement_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='export_logs_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='flagged_message_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='geo_fenced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='geo_radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='hotline_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='hub_purpose',
            field=models.CharField(choices=[('SECURITY', 'Security'), ('EMERGENCY', 'Emergency'), ('COMMUNITY', 'Community'), ('TRAFFIC', 'Traffic'), ('ALERTS', 'Alerts')], db_index=True, default='COMMUNITY', max_length=20),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='join_mode',
            field=models.CharField(choices=[('OPEN', 'Open'), ('REQUEST', 'Request'), ('APPROVAL', 'Approval')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='last_security_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='link_whitelist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='link_whitelist_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='location_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='max_daily_reports_per_user',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='members_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='message_requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='messages_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='min_account_age_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='new_members_7d',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='ownership_transfer_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='privacy',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('INVITE_ONLY', 'Invite Only')], db_index=True, default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='profanity_filter_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='rapid_response_team_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='rate_limit_per_user_per_minute',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='requires_identity_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='requires_location_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='requires_phone_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='rules',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='slow_mode_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='sponsor_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='subscription_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='trending_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='trust_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='UNVERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityhub',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hubmessage',
            name='forwarded_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='communityhub',
            name='hub_type',
            field=models.CharField(choices=[('SYSTEM', 'System (Geographic)'), ('LOCAL', 'Local / User Created')], db_index=True, default='LOCAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='hubmessage',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='community.hubmessage'),
        ),
        migrations.AddIndex(
            model_name='communityhub',
            index=models.Index(fields=['hub_type', 'is_active'], name='community_c_hub_typ_bd2099_idx'),
        ),
        migrations.AddIndex(
            model_name='communityhub',
            index=models.Index(fields=['privacy', 'join_mode'], name='community_c_privacy_15054a_idx'),
        ),
        migrations.AddIndex(
            model_name='communityhub',
            index=models.Index(fields=['verification_status'], name='community_c_verific_792803_idx'),
        ),
        migrations.AddIndex(
            model_name='communityhub',
            index=models.Index(fields=['hub_purpose'], name='community_c_hub_pur_5a6da9_idx'),
        ),
        migrations.AddIndex(
            model_name='communityhub',
            index=models.Index(fields=['name'], name='community_c_name_5f9b38_idx'),
        ),
    ]
