# Generated by Django 5.2.9 on 2026-02-01 08:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_communityhub_active_members_7d_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyShareSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_sessions', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_received_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_conversations_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_conversations_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='community.privateconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('MEDIA', 'Media'), ('SYSTEM', 'System')], db_index=True, default='TEXT', max_length=20)),
                ('text', models.TextField(blank=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_temp_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community.privateconversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='community.privatemessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FILE', 'File')], db_index=True, max_length=20)),
                ('url', models.URLField()),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='community.privatemessage')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessageHidden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='community.privatemessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_private_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.privatemessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessageReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='community.privatemessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_message_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='privateconversation',
            index=models.Index(fields=['user1', 'updated_at'], name='community_p_user1_i_efd9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='privateconversation',
            index=models.Index(fields=['user2', 'updated_at'], name='community_p_user2_i_8f59e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='privateconversation',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_private_conversation_pair'),
        ),
        migrations.AddIndex(
            model_name='privateconversationmember',
            index=models.Index(fields=['user', 'pinned_at'], name='community_p_user_id_d11f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='privateconversationmember',
            index=models.Index(fields=['user', 'archived_at'], name='community_p_user_id_1e665d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privateconversationmember',
            unique_together={('user', 'conversation')},
        ),
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['conversation', '-created_at'], name='community_p_convers_5c375b_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['sender', '-created_at'], name='community_p_sender__8ffafb_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessageattachment',
            index=models.Index(fields=['message', 'attachment_type'], name='community_p_message_6946bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privatemessagehidden',
            unique_together={('message', 'user')},
        ),
        migrations.AddConstraint(
            model_name='privatemessagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_one_private_reaction_per_user_per_message'),
        ),
        migrations.AddIndex(
            model_name='privatemessagereceipt',
            index=models.Index(fields=['message', 'user'], name='community_p_message_dcf27c_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessagereceipt',
            index=models.Index(fields=['message', 'read_at'], name='community_p_message_faef50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privatemessagereceipt',
            unique_together={('message', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together={('blocker', 'blocked')},
        ),
    ]
