# Generated by Django 5.2.9 on 2026-02-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_emergencysharesession_privateconversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubmessagereceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
