# Generated by Django 5.2.9 on 2026-01-27 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SosDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('severity_level', models.CharField(blank=True, max_length=10, null=True)),
                ('severity_score', models.FloatField(blank=True, null=True)),
                ('signal_quality', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SosMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=10)),
                ('file', models.FileField(upload_to='sos/pre/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Audio/Video duration in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='sos.sosdraft')),
            ],
        ),
        migrations.AddIndex(
            model_name='sosdraft',
            index=models.Index(fields=['user', 'status'], name='sos_sosdraf_user_id_0fcb30_idx'),
        ),
        migrations.AddIndex(
            model_name='sosdraft',
            index=models.Index(fields=['created_at'], name='sos_sosdraf_created_2ea497_idx'),
        ),
        migrations.AddIndex(
            model_name='sosmedia',
            index=models.Index(fields=['media_type'], name='sos_sosmedi_media_t_c77526_idx'),
        ),
        migrations.AddIndex(
            model_name='sosmedia',
            index=models.Index(fields=['created_at'], name='sos_sosmedi_created_e0b310_idx'),
        ),
    ]
