# Generated by Django 5.2.9 on 2026-01-27 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_sosdraft_sosmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='draft',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sos', to='sos.sosdraft'),
            preserve_default=False,
        ),
    ]
